### ISSUE TITLE
v1.3.1

### ISSUE THREAD

**Issue by yomichi** [cmsi/ma-tenes#1]
@wistaria 
リリースされましたので、アップデートしていただけると幸いです。
（ハンズオンが 2022-10-25 (Tue.) にあるのでよろしくおねがいします）

**Comment by wistaria** [comment]
@yomichi 
アップデートしました https://github.com/cmsi/MateriAppsPackages/releases/tag/tenes-1.3.1-1
なお、ma-* のリポジトリが増えすぎてよく分からなくなってきたので、 https://github.com/cmsi/MateriAppsPackages に統合しつつあります
